import type { FeedItem } from './types';

export const MOCK_FEEDS = [
  {
    id: 'f1',
    location: '망원동 센토브',
    title: '기획 디쟌 대면 회의',
    participantAvatarUrls: [
      'https://picsum.photos/seed/p1/48',
      'https://picsum.photos/seed/p2/48',
      'https://picsum.photos/seed/p3/48',
      'https://picsum.photos/seed/p4/48',
    ],
    date: '2026.04.30',
    thumbnailUrl: 'https://picsum.photos/seed/feed1/300',
    photoCount: 4,
  },
  {
    id: 'f2',
    location: '마포한강공원',
    title: '티키탁 다같이 한강 나들이',
    participantAvatarUrls: [
      'https://picsum.photos/seed/p1/48',
      'https://picsum.photos/seed/p2/48',
      'https://picsum.photos/seed/p3/48',
      'https://picsum.photos/seed/p4/48',
      'https://picsum.photos/seed/p5/48',
      'https://picsum.photos/seed/p6/48',
      'https://picsum.photos/seed/p7/48',
      'https://picsum.photos/seed/p8/48',
    ],
    date: '2026.04.23',
    thumbnailUrl: 'https://picsum.photos/seed/feed2/300',
    photoCount: 11,
  },
  {
    id: 'f3',
    location: '홍대입구 9번 출구',
    title: '프론트 4차 회의',
    participantAvatarUrls: [
      'https://picsum.photos/seed/p1/48',
      'https://picsum.photos/seed/p2/48',
      'https://picsum.photos/seed/p3/48',
    ],
    date: '2026.04.17',
    thumbnailUrl: 'https://picsum.photos/seed/feed3/300',
    photoCount: 2,
  },
  {
    id: 'f4',
    location: '공덕역 1번 출구',
    title: '대면 회의',
    participantAvatarUrls: [
      'https://picsum.photos/seed/p1/48',
      'https://picsum.photos/seed/p2/48',
      'https://picsum.photos/seed/p3/48',
      'https://picsum.photos/seed/p4/48',
      'https://picsum.photos/seed/p5/48',
      'https://picsum.photos/seed/p6/48',
    ],
    date: '2026.04.14',
    thumbnailUrl: 'https://picsum.photos/seed/feed4/300',
    photoCount: 13,
  },
  {
    id: 'f5',
    location: '연남동 카페거리',
    title: '주말 브런치 모임',
    participantAvatarUrls: [
      'https://picsum.photos/seed/p2/48',
      'https://picsum.photos/seed/p4/48',
      'https://picsum.photos/seed/p7/48',
      'https://picsum.photos/seed/p9/48',
      'https://picsum.photos/seed/p11/48',
    ],
    date: '2026.04.10',
    thumbnailUrl: 'https://picsum.photos/seed/feed5/300',
    photoCount: 7,
  },
  {
    id: 'f6',
    location: '서울숲',
    title: '봄꽃 산책 OOTD',
    participantAvatarUrls: [
      'https://picsum.photos/seed/p3/48',
      'https://picsum.photos/seed/p5/48',
      'https://picsum.photos/seed/p8/48',
    ],
    date: '2026.04.05',
    thumbnailUrl: 'https://picsum.photos/seed/feed6/300',
    photoCount: 18,
  },
  {
    id: 'f7',
    location: '강남역 2번 출구',
    title: '디자인 시스템 워크샵',
    participantAvatarUrls: [
      'https://picsum.photos/seed/p1/48',
      'https://picsum.photos/seed/p2/48',
      'https://picsum.photos/seed/p3/48',
      'https://picsum.photos/seed/p4/48',
      'https://picsum.photos/seed/p5/48',
      'https://picsum.photos/seed/p6/48',
      'https://picsum.photos/seed/p7/48',
      'https://picsum.photos/seed/p8/48',
      'https://picsum.photos/seed/p9/48',
      'https://picsum.photos/seed/p10/48',
    ],
    date: '2026.03.28',
    thumbnailUrl: 'https://picsum.photos/seed/feed7/300',
    photoCount: 32,
  },
  {
    id: 'f8',
    location: '잠실종합운동장',
    title: '풋살 정기 모임',
    participantAvatarUrls: [
      'https://picsum.photos/seed/p4/48',
      'https://picsum.photos/seed/p6/48',
      'https://picsum.photos/seed/p9/48',
      'https://picsum.photos/seed/p12/48',
    ],
    date: '2026.03.21',
    thumbnailUrl: 'https://picsum.photos/seed/feed8/300',
    photoCount: 9,
  },
  {
    id: 'f9',
    location: '성수동 카페',
    title: '월간 회고 데이',
    participantAvatarUrls: [
      'https://picsum.photos/seed/p2/48',
      'https://picsum.photos/seed/p5/48',
      'https://picsum.photos/seed/p7/48',
      'https://picsum.photos/seed/p10/48',
      'https://picsum.photos/seed/p13/48',
      'https://picsum.photos/seed/p14/48',
    ],
    date: '2026.03.15',
    thumbnailUrl: 'https://picsum.photos/seed/feed9/300',
    photoCount: 5,
  },
  {
    id: 'f10',
    location: '북촌한옥마을',
    title: '한옥 사진 출사',
    participantAvatarUrls: [
      'https://picsum.photos/seed/p1/48',
      'https://picsum.photos/seed/p3/48',
      'https://picsum.photos/seed/p8/48',
      'https://picsum.photos/seed/p11/48',
      'https://picsum.photos/seed/p15/48',
    ],
    date: '2026.03.08',
    thumbnailUrl: 'https://picsum.photos/seed/feed10/300',
    photoCount: 24,
  },
  {
    id: 'f11',
    location: '여의도 IFC몰',
    title: '점심 회식',
    participantAvatarUrls: [
      'https://picsum.photos/seed/p2/48',
      'https://picsum.photos/seed/p4/48',
      'https://picsum.photos/seed/p6/48',
      'https://picsum.photos/seed/p8/48',
      'https://picsum.photos/seed/p10/48',
      'https://picsum.photos/seed/p12/48',
      'https://picsum.photos/seed/p14/48',
    ],
    date: '2026.02.27',
    thumbnailUrl: 'https://picsum.photos/seed/feed11/300',
    photoCount: 6,
  },
  {
    id: 'f12',
    location: '이태원 글로벌라운지',
    title: '네트워킹 파티',
    participantAvatarUrls: [
      'https://picsum.photos/seed/p1/48',
      'https://picsum.photos/seed/p2/48',
      'https://picsum.photos/seed/p3/48',
    ],
    date: '2026.02.20',
    thumbnailUrl: 'https://picsum.photos/seed/feed12/300',
    photoCount: 41,
  },
  {
    id: 'f13',
    location: '광화문 광장',
    title: '주말 야경 투어',
    participantAvatarUrls: [
      'https://picsum.photos/seed/p4/48',
      'https://picsum.photos/seed/p7/48',
      'https://picsum.photos/seed/p9/48',
      'https://picsum.photos/seed/p11/48',
    ],
    date: '2026.02.14',
    thumbnailUrl: 'https://picsum.photos/seed/feed13/300',
    photoCount: 15,
  },
] satisfies FeedItem[];
